batch_size: 40
epochs: 40
loss: mse_cosine
optimizer:
  amsgrad: false
  beta_1: 0.9
  beta_2: 0.999
  decay: 0.0
  epsilon: 1.0e-07
  learning_rate: 0.001
  name: Adam
roi: ROI_VC
val_batch_size: 20
