batch_size: 75
bins:
- -0.9
- -0.7
- -0.5
- -0.3
- -0.1
- 0.1
- 0.3
- 0.5
- 0.7
- 0.9
epochs: 20
loss: mse_cosine
optimizer:
  clipvalue: 0.5
  decay: 0.005
  learning_rate: 0.1
  momentum: 0.9
  name: SGD
  nesterov: true
val_batch_size: 50
