batch_size: 75
epochs: 10
loss:
  name: mean_squared_error
  reduction: auto
optimizer:
  clipvalue: 0.5
  decay: 0.01
  learning_rate: 0.1
  momentum: 0.9
  name: SGD
  nesterov: true
val_batch_size: 50
